// <auto-generated-once>
//   Initial content generated from grob-error-codes.md (94 codes) under D-308.
//   AFTER the initial commit this file is HAND-MAINTAINED. Do not regenerate.
//   The ErrorCatalog <-> registry agreement test (Grob.Core.Tests) is the guard:
//   add a descriptor here and a row to grob-error-codes.md in the same change.
// </auto-generated-once>

namespace Grob.Core;

/// <summary>
/// The single source of truth, in code, for every diagnostic Grob can emit.
/// Each field mirrors one row of the error-code registry (grob-error-codes.md).
/// Components raise diagnostics by referencing a descriptor, never a code literal,
/// so the string "Exxxx" appears exactly once per code across the whole solution.
/// Governed by ADR-0014 (numbering) and ADR-0017 (stability); see D-308.
/// </summary>
public static class ErrorCatalog {
    // ---- Type errors — E0001–E0999 ----

    /// <summary>type mismatch</summary>
    public static readonly ErrorDescriptor E0001 = new(
        Code: "E0001",
        Title: "type mismatch",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>incompatible operands</summary>
    public static readonly ErrorDescriptor E0002 = new(
        Code: "E0002",
        Title: "incompatible operands",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>wrong number of arguments</summary>
    public static readonly ErrorDescriptor E0003 = new(
        Code: "E0003",
        Title: "wrong number of arguments",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>argument type mismatch</summary>
    public static readonly ErrorDescriptor E0004 = new(
        Code: "E0004",
        Title: "argument type mismatch",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>return type mismatch</summary>
    public static readonly ErrorDescriptor E0005 = new(
        Code: "E0005",
        Title: "return type mismatch",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>undefined method on type</summary>
    public static readonly ErrorDescriptor E0006 = new(
        Code: "E0006",
        Title: "undefined method on type",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>invalid implicit conversion</summary>
    public static readonly ErrorDescriptor E0007 = new(
        Code: "E0007",
        Title: "invalid implicit conversion",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>named argument before positional</summary>
    public static readonly ErrorDescriptor E0008 = new(
        Code: "E0008",
        Title: "named argument before positional",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>named argument names a required parameter</summary>
    public static readonly ErrorDescriptor E0009 = new(
        Code: "E0009",
        Title: "named argument names a required parameter",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>duplicate named argument</summary>
    public static readonly ErrorDescriptor E0010 = new(
        Code: "E0010",
        Title: "duplicate named argument",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>unknown parameter name</summary>
    public static readonly ErrorDescriptor E0011 = new(
        Code: "E0011",
        Title: "unknown parameter name",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>nil dereference without `?.` or `??`</summary>
    public static readonly ErrorDescriptor E0101 = new(
        Code: "E0101",
        Title: "nil dereference without `?.` or `??`",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>nullable interpolation</summary>
    public static readonly ErrorDescriptor E0102 = new(
        Code: "E0102",
        Title: "nullable interpolation",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>non-nullable field requires initialiser</summary>
    public static readonly ErrorDescriptor E0103 = new(
        Code: "E0103",
        Title: "non-nullable field requires initialiser",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>nullable type used where non-nullable required</summary>
    public static readonly ErrorDescriptor E0104 = new(
        Code: "E0104",
        Title: "nullable type used where non-nullable required",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>reassignment of `const` binding</summary>
    public static readonly ErrorDescriptor E0201 = new(
        Code: "E0201",
        Title: "reassignment of `const` binding",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>reassignment of `readonly` binding</summary>
    public static readonly ErrorDescriptor E0202 = new(
        Code: "E0202",
        Title: "reassignment of `readonly` binding",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>reassignment of `param` binding</summary>
    public static readonly ErrorDescriptor E0203 = new(
        Code: "E0203",
        Title: "reassignment of `param` binding",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>mutation of `readonly` value</summary>
    public static readonly ErrorDescriptor E0204 = new(
        Code: "E0204",
        Title: "mutation of `readonly` value",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>non-constant expression in `const` right-hand side</summary>
    public static readonly ErrorDescriptor E0205 = new(
        Code: "E0205",
        Title: "non-constant expression in `const` right-hand side",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>type cycle with no terminating field</summary>
    public static readonly ErrorDescriptor E0301 = new(
        Code: "E0301",
        Title: "type cycle with no terminating field",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>recursive type without indirection</summary>
    public static readonly ErrorDescriptor E0302 = new(
        Code: "E0302",
        Title: "recursive type without indirection",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>circular type dependency among top-level value bindings</summary>
    public static readonly ErrorDescriptor E0303 = new(
        Code: "E0303",
        Title: "circular type dependency among top-level value bindings",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>generic type argument count mismatch</summary>
    public static readonly ErrorDescriptor E0401 = new(
        Code: "E0401",
        Title: "generic type argument count mismatch",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>generic constraint violation</summary>
    public static readonly ErrorDescriptor E0402 = new(
        Code: "E0402",
        Title: "generic constraint violation",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`for...in` subject is not iterable</summary>
    public static readonly ErrorDescriptor E0501 = new(
        Code: "E0501",
        Title: "`for...in` subject is not iterable",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>single-identifier `for...in` over a `map`</summary>
    public static readonly ErrorDescriptor E0502 = new(
        Code: "E0502",
        Title: "single-identifier `for...in` over a `map`",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>descending range without explicit negative `step`</summary>
    public static readonly ErrorDescriptor E0503 = new(
        Code: "E0503",
        Title: "descending range without explicit negative `step`",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>reassignment of `for...in` iterator variable</summary>
    public static readonly ErrorDescriptor E0504 = new(
        Code: "E0504",
        Title: "reassignment of `for...in` iterator variable",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>non-exhaustive switch expression</summary>
    public static readonly ErrorDescriptor E0505 = new(
        Code: "E0505",
        Title: "non-exhaustive switch expression",
        Category: ErrorCategory.Type,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    // ---- Name resolution — E1001–E1999 ----

    /// <summary>undefined identifier</summary>
    public static readonly ErrorDescriptor E1001 = new(
        Code: "E1001",
        Title: "undefined identifier",
        Category: ErrorCategory.NameResolution,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>undefined member</summary>
    public static readonly ErrorDescriptor E1002 = new(
        Code: "E1002",
        Title: "undefined member",
        Category: ErrorCategory.NameResolution,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>undefined module</summary>
    public static readonly ErrorDescriptor E1003 = new(
        Code: "E1003",
        Title: "undefined module",
        Category: ErrorCategory.NameResolution,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>shadowed declaration</summary>
    public static readonly ErrorDescriptor E1101 = new(
        Code: "E1101",
        Title: "shadowed declaration",
        Category: ErrorCategory.NameResolution,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Warning,
        Throws: null);

    /// <summary>variable already declared in this scope</summary>
    public static readonly ErrorDescriptor E1102 = new(
        Code: "E1102",
        Title: "variable already declared in this scope",
        Category: ErrorCategory.NameResolution,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>reserved identifier used as a binding name</summary>
    public static readonly ErrorDescriptor E1103 = new(
        Code: "E1103",
        Title: "reserved identifier used as a binding name",
        Category: ErrorCategory.NameResolution,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>forward reference inside function body</summary>
    public static readonly ErrorDescriptor E1201 = new(
        Code: "E1201",
        Title: "forward reference inside function body",
        Category: ErrorCategory.NameResolution,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>use before declaration in block scope</summary>
    public static readonly ErrorDescriptor E1202 = new(
        Code: "E1202",
        Title: "use before declaration in block scope",
        Category: ErrorCategory.NameResolution,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    // ---- Syntax — E2001–E2999 ----

    /// <summary>unexpected token</summary>
    public static readonly ErrorDescriptor E2001 = new(
        Code: "E2001",
        Title: "unexpected token",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>unterminated string literal</summary>
    public static readonly ErrorDescriptor E2002 = new(
        Code: "E2002",
        Title: "unterminated string literal",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>unterminated block comment</summary>
    public static readonly ErrorDescriptor E2003 = new(
        Code: "E2003",
        Title: "unterminated block comment",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>unterminated raw string</summary>
    public static readonly ErrorDescriptor E2004 = new(
        Code: "E2004",
        Title: "unterminated raw string",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>invalid escape sequence</summary>
    public static readonly ErrorDescriptor E2005 = new(
        Code: "E2005",
        Title: "invalid escape sequence",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>invalid numeric literal</summary>
    public static readonly ErrorDescriptor E2006 = new(
        Code: "E2006",
        Title: "invalid numeric literal",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>invalid regex flag</summary>
    public static readonly ErrorDescriptor E2007 = new(
        Code: "E2007",
        Title: "invalid regex flag",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>unterminated regex literal</summary>
    public static readonly ErrorDescriptor E2008 = new(
        Code: "E2008",
        Title: "unterminated regex literal",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>unterminated string interpolation</summary>
    public static readonly ErrorDescriptor E2009 = new(
        Code: "E2009",
        Title: "unterminated string interpolation",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>unexpected character</summary>
    public static readonly ErrorDescriptor E2010 = new(
        Code: "E2010",
        Title: "unexpected character",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>stray semicolon</summary>
    public static readonly ErrorDescriptor E2011 = new(
        Code: "E2011",
        Title: "stray semicolon",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`#` not followed by `{`</summary>
    public static readonly ErrorDescriptor E2012 = new(
        Code: "E2012",
        Title: "`#` not followed by `{`",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>single-character operator requires doubling</summary>
    public static readonly ErrorDescriptor E2013 = new(
        Code: "E2013",
        Title: "single-character operator requires doubling",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>unbalanced closing bracket</summary>
    public static readonly ErrorDescriptor E2014 = new(
        Code: "E2014",
        Title: "unbalanced closing bracket",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>bare `{` cannot begin an expression</summary>
    public static readonly ErrorDescriptor E2101 = new(
        Code: "E2101",
        Title: "bare `{` cannot begin an expression",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>empty type construction missing `{ }`</summary>
    public static readonly ErrorDescriptor E2102 = new(
        Code: "E2102",
        Title: "empty type construction missing `{ }`",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`import` after declaration</summary>
    public static readonly ErrorDescriptor E2201 = new(
        Code: "E2201",
        Title: "`import` after declaration",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`param` after `fn` or top-level statement</summary>
    public static readonly ErrorDescriptor E2202 = new(
        Code: "E2202",
        Title: "`param` after `fn` or top-level statement",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>top-level `return`</summary>
    public static readonly ErrorDescriptor E2203 = new(
        Code: "E2203",
        Title: "top-level `return`",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`try` without `catch` or `finally`</summary>
    public static readonly ErrorDescriptor E2204 = new(
        Code: "E2204",
        Title: "`try` without `catch` or `finally`",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`catch` after catch-all</summary>
    public static readonly ErrorDescriptor E2205 = new(
        Code: "E2205",
        Title: "`catch` after catch-all",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`finally` not last in `try`</summary>
    public static readonly ErrorDescriptor E2206 = new(
        Code: "E2206",
        Title: "`finally` not last in `try`",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`return` / `break` / `continue` inside `finally`</summary>
    public static readonly ErrorDescriptor E2207 = new(
        Code: "E2207",
        Title: "`return` / `break` / `continue` inside `finally`",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>duplicate field name in type declaration</summary>
    public static readonly ErrorDescriptor E2208 = new(
        Code: "E2208",
        Title: "duplicate field name in type declaration",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>trailing comma not permitted here</summary>
    public static readonly ErrorDescriptor E2209 = new(
        Code: "E2209",
        Title: "trailing comma not permitted here",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>line continuation rule violation</summary>
    public static readonly ErrorDescriptor E2210 = new(
        Code: "E2210",
        Title: "line continuation rule violation",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`break` inside `select`</summary>
    public static readonly ErrorDescriptor E2211 = new(
        Code: "E2211",
        Title: "`break` inside `select`",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`break` / `continue` outside a loop</summary>
    public static readonly ErrorDescriptor E2212 = new(
        Code: "E2212",
        Title: "`break` / `continue` outside a loop",
        Category: ErrorCategory.Syntax,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    // ---- Module / import — E3001–E3999 ----

    /// <summary>unknown plugin</summary>
    public static readonly ErrorDescriptor E3001 = new(
        Code: "E3001",
        Title: "unknown plugin",
        Category: ErrorCategory.Module,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>plugin not installed</summary>
    public static readonly ErrorDescriptor E3002 = new(
        Code: "E3002",
        Title: "plugin not installed",
        Category: ErrorCategory.Module,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>circular import</summary>
    public static readonly ErrorDescriptor E3003 = new(
        Code: "E3003",
        Title: "circular import",
        Category: ErrorCategory.Module,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>invalid module alias</summary>
    public static readonly ErrorDescriptor E3004 = new(
        Code: "E3004",
        Title: "invalid module alias",
        Category: ErrorCategory.Module,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>ambiguous unqualified type reference</summary>
    public static readonly ErrorDescriptor E3101 = new(
        Code: "E3101",
        Title: "ambiguous unqualified type reference",
        Category: ErrorCategory.Module,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>plugin type collides with stdlib type</summary>
    public static readonly ErrorDescriptor E3102 = new(
        Code: "E3102",
        Title: "plugin type collides with stdlib type",
        Category: ErrorCategory.Module,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>manifest version mismatch</summary>
    public static readonly ErrorDescriptor E3201 = new(
        Code: "E3201",
        Title: "manifest version mismatch",
        Category: ErrorCategory.Module,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    // ---- Param / decorator — E4001–E4999 ----

    /// <summary>unknown decorator</summary>
    public static readonly ErrorDescriptor E4001 = new(
        Code: "E4001",
        Title: "unknown decorator",
        Category: ErrorCategory.ParamDecorator,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>decorator not permitted here</summary>
    public static readonly ErrorDescriptor E4002 = new(
        Code: "E4002",
        Title: "decorator not permitted here",
        Category: ErrorCategory.ParamDecorator,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>invalid `@allowed` argument</summary>
    public static readonly ErrorDescriptor E4101 = new(
        Code: "E4101",
        Title: "invalid `@allowed` argument",
        Category: ErrorCategory.ParamDecorator,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>invalid `@minLength` / `@maxLength` argument</summary>
    public static readonly ErrorDescriptor E4102 = new(
        Code: "E4102",
        Title: "invalid `@minLength` / `@maxLength` argument",
        Category: ErrorCategory.ParamDecorator,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`param` block syntax error</summary>
    public static readonly ErrorDescriptor E4201 = new(
        Code: "E4201",
        Title: "`param` block syntax error",
        Category: ErrorCategory.ParamDecorator,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>`param` after `param` block ends</summary>
    public static readonly ErrorDescriptor E4202 = new(
        Code: "E4202",
        Title: "`param` after `param` block ends",
        Category: ErrorCategory.ParamDecorator,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    // ---- Runtime — E5001–E5999 ----

    /// <summary>integer overflow</summary>
    public static readonly ErrorDescriptor E5001 = new(
        Code: "E5001",
        Title: "integer overflow",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ArithmeticError);

    /// <summary>integer division by zero</summary>
    public static readonly ErrorDescriptor E5002 = new(
        Code: "E5002",
        Title: "integer division by zero",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ArithmeticError);

    /// <summary>integer modulo by zero</summary>
    public static readonly ErrorDescriptor E5003 = new(
        Code: "E5003",
        Title: "integer modulo by zero",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ArithmeticError);

    /// <summary>float division by zero</summary>
    public static readonly ErrorDescriptor E5004 = new(
        Code: "E5004",
        Title: "float division by zero",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ArithmeticError);

    /// <summary>float modulo by zero</summary>
    public static readonly ErrorDescriptor E5005 = new(
        Code: "E5005",
        Title: "float modulo by zero",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ArithmeticError);

    /// <summary>math domain violation</summary>
    public static readonly ErrorDescriptor E5006 = new(
        Code: "E5006",
        Title: "math domain violation",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ArithmeticError);

    /// <summary>array index out of range</summary>
    public static readonly ErrorDescriptor E5101 = new(
        Code: "E5101",
        Title: "array index out of range",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.IndexError);

    /// <summary>substring bounds out of range</summary>
    public static readonly ErrorDescriptor E5102 = new(
        Code: "E5102",
        Title: "substring bounds out of range",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.IndexError);

    /// <summary>nil dereference at runtime</summary>
    public static readonly ErrorDescriptor E5201 = new(
        Code: "E5201",
        Title: "nil dereference at runtime",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.NilError);

    /// <summary>file not found</summary>
    public static readonly ErrorDescriptor E5301 = new(
        Code: "E5301",
        Title: "file not found",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.IoError);

    /// <summary>permission denied</summary>
    public static readonly ErrorDescriptor E5302 = new(
        Code: "E5302",
        Title: "permission denied",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.IoError);

    /// <summary>path is a directory, file expected</summary>
    public static readonly ErrorDescriptor E5303 = new(
        Code: "E5303",
        Title: "path is a directory, file expected",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.IoError);

    /// <summary>path is a file, directory expected</summary>
    public static readonly ErrorDescriptor E5304 = new(
        Code: "E5304",
        Title: "path is a file, directory expected",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.IoError);

    /// <summary>I/O failure (residual)</summary>
    public static readonly ErrorDescriptor E5305 = new(
        Code: "E5305",
        Title: "I/O failure (residual)",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.IoError);

    /// <summary>network connection failed</summary>
    public static readonly ErrorDescriptor E5401 = new(
        Code: "E5401",
        Title: "network connection failed",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.NetworkError);

    /// <summary>HTTP error response</summary>
    public static readonly ErrorDescriptor E5402 = new(
        Code: "E5402",
        Title: "HTTP error response",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.NetworkError);

    /// <summary>DNS resolution failed</summary>
    public static readonly ErrorDescriptor E5403 = new(
        Code: "E5403",
        Title: "DNS resolution failed",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.NetworkError);

    /// <summary>network timeout</summary>
    public static readonly ErrorDescriptor E5404 = new(
        Code: "E5404",
        Title: "network timeout",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.NetworkError);

    /// <summary>JSON parse error</summary>
    public static readonly ErrorDescriptor E5501 = new(
        Code: "E5501",
        Title: "JSON parse error",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.JsonError);

    /// <summary>JSON type coercion failure</summary>
    public static readonly ErrorDescriptor E5502 = new(
        Code: "E5502",
        Title: "JSON type coercion failure",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.JsonError);

    /// <summary>process timeout</summary>
    public static readonly ErrorDescriptor E5601 = new(
        Code: "E5601",
        Title: "process timeout",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ProcessError);

    /// <summary>process exit non-zero (under `OrFail`)</summary>
    public static readonly ErrorDescriptor E5602 = new(
        Code: "E5602",
        Title: "process exit non-zero (under `OrFail`)",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ProcessError);

    /// <summary>process spawn failed</summary>
    public static readonly ErrorDescriptor E5603 = new(
        Code: "E5603",
        Title: "process spawn failed",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ProcessError);

    /// <summary>guid parse error</summary>
    public static readonly ErrorDescriptor E5701 = new(
        Code: "E5701",
        Title: "guid parse error",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ParseError);

    /// <summary>parse error (residual)</summary>
    public static readonly ErrorDescriptor E5702 = new(
        Code: "E5702",
        Title: "parse error (residual)",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.ParseError);

    /// <summary>required environment variable not set</summary>
    public static readonly ErrorDescriptor E5801 = new(
        Code: "E5801",
        Title: "required environment variable not set",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.LookupError);

    /// <summary>call stack overflow</summary>
    public static readonly ErrorDescriptor E5901 = new(
        Code: "E5901",
        Title: "call stack overflow",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.RuntimeError);

    /// <summary>circular initialisation</summary>
    public static readonly ErrorDescriptor E5902 = new(
        Code: "E5902",
        Title: "circular initialisation",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.RuntimeError);

    /// <summary>runtime failure (residual catch-all)</summary>
    public static readonly ErrorDescriptor E5903 = new(
        Code: "E5903",
        Title: "runtime failure (residual catch-all)",
        Category: ErrorCategory.Runtime,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: GrobErrorLeaf.RuntimeError);

    // ---- Internal compiler error — E9001–E9999 ----

    /// <summary>internal compiler error — please report</summary>
    public static readonly ErrorDescriptor E9001 = new(
        Code: "E9001",
        Title: "internal compiler error — please report",
        Category: ErrorCategory.Internal,
        Status: ErrorStatus.PreRelease,
        Severity: DiagnosticSeverity.Error,
        Throws: null);

    /// <summary>Every descriptor, in registry order. Used by the agreement test.</summary>
    public static readonly IReadOnlyList<ErrorDescriptor> All = new[] {
        E0001,
        E0002,
        E0003,
        E0004,
        E0005,
        E0006,
        E0007,
        E0008,
        E0009,
        E0010,
        E0011,
        E0101,
        E0102,
        E0103,
        E0104,
        E0201,
        E0202,
        E0203,
        E0204,
        E0205,
        E0301,
        E0302,
        E0303,
        E0401,
        E0402,
        E0501,
        E0502,
        E0503,
        E0504,
        E0505,
        E1001,
        E1002,
        E1003,
        E1101,
        E1102,
        E1103,
        E1201,
        E1202,
        E2001,
        E2002,
        E2003,
        E2004,
        E2005,
        E2006,
        E2007,
        E2008,
        E2009,
        E2010,
        E2011,
        E2012,
        E2013,
        E2014,
        E2101,
        E2102,
        E2201,
        E2202,
        E2203,
        E2204,
        E2205,
        E2206,
        E2207,
        E2208,
        E2209,
        E2210,
        E2211,
        E2212,
        E3001,
        E3002,
        E3003,
        E3004,
        E3101,
        E3102,
        E3201,
        E4001,
        E4002,
        E4101,
        E4102,
        E4201,
        E4202,
        E5001,
        E5002,
        E5003,
        E5004,
        E5005,
        E5006,
        E5101,
        E5102,
        E5201,
        E5301,
        E5302,
        E5303,
        E5304,
        E5305,
        E5401,
        E5402,
        E5403,
        E5404,
        E5501,
        E5502,
        E5601,
        E5602,
        E5603,
        E5701,
        E5702,
        E5801,
        E5901,
        E5902,
        E5903,
        E9001,
    };
}
